# Generated by Django 5.1.4 on 2025-01-21 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todo',
            options={'ordering': ['-updated_at']},
        ),
    ]
